/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Lib.database;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author nanda
 */
public class Debug extends javax.swing.JFrame {

    /**
     * Creates new form Debug
     */
    public Debug() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnResetAkun = new javax.swing.JButton();
        btnResetTransaksi = new javax.swing.JButton();
        btnResetMenu = new javax.swing.JButton();

        setAlwaysOnTop(true);

        btnResetAkun.setText("Reset Database Akun");
        btnResetAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAkunActionPerformed(evt);
            }
        });

        btnResetTransaksi.setText("Reset  Database Transaksi");

        btnResetMenu.setText("Reset Database Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnResetAkun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetMenu)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAkunActionPerformed
        try {
        int confirmation = JOptionPane.showConfirmDialog(
            this, // Parent component
            "Are you sure you want to delete all data in the person table?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirmation == JOptionPane.YES_OPTION) {           
            Connection connection = database.getConnection();

            PreparedStatement st = connection.prepareStatement("DELETE FROM person");
            int rowsAffected = st.executeUpdate();

            PreparedStatement resetAutoIncrement = connection.prepareStatement("ALTER TABLE person AUTO_INCREMENT = 1");
            resetAutoIncrement.executeUpdate();

            JOptionPane.showMessageDialog(
                this, 
                "All data in the person table has been deleted. Rows affected: " + rowsAffected, 
                "Operation Successful", 
                JOptionPane.INFORMATION_MESSAGE
            );

            st.close();
            resetAutoIncrement.close();
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(
            this, 
            "An error occurred while deleting data: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(
            this, 
            "An unexpected error occurred: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnResetAkunActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetAkun;
    private javax.swing.JButton btnResetMenu;
    private javax.swing.JButton btnResetTransaksi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
